Repository openSUSE/wicked, pull requests merged in 2023-01, with the labels that each got.

#942 ifstatus: improve to show a no-carrier status
  client/ifstatus.c
  include/wicked/constants.h
Labels: enhancement

#945 nanny: fix use-after-free in debug mode (bsc#1206447)
  nanny/policy.c
Labels: bug

#946 client: add firmware extensions|interfaces command (jsc#PED-3132)
  client/Makefile.am
  client/firmware.c
  client/main.c
  client/main.h
  client/read-config.c
  client/read-config.h
  include/wicked/netinfo.h
  src/Makefile.am
  src/firmware.c
  src/firmware.h
Labels: feature

#947 client: add firmware enable|disable command (jsc#PED-3132)
  client/firmware.c
  client/redfish.c
  configure.ac
  etc/client.xml.in
  src/Makefile.am
  src/appconfig.c
  src/appconfig.h
  src/dbus-objects/model.c
  src/dbus-objects/naming.c
  src/extension.c
  src/extension.h
  src/firmware.c
  src/update.c
  wicked.spec.in
Labels: feature

#948 extensions: add nbft extension (jsc#PED-3132)
  etc/client.xml.in
  extensions/Makefile.am
  extensions/nbft
  testing/Makefile.am
  testing/nbft-test.sh
  testing/nbft/dhcp-broken-json-01/nbft-hfi.json
  testing/nbft/dhcp-broken-json-01/nbft.out
  testing/nbft/dhcp-no-index/nbft-hfi.json
  testing/nbft/dhcp-no-index/nbft.out
  testing/nbft/dhcp-no-mac/nbft-hfi.json
  testing/nbft/dhcp-no-mac/nbft.out
  testing/nbft/dhcp-routed/nbft-hfi.json
  testing/nbft/dhcp-routed/nbft.out
  testing/nbft/dhcp-simple/nbft-hfi.json
  testing/nbft/dhcp-simple/nbft.out
  testing/nbft/dhcp-vlan/nbft-hfi.json
  testing/nbft/dhcp-vlan/nbft.out
  testing/nbft/static-bad-gateway/nbft-hfi.json
  testing/nbft/static-bad-gateway/nbft.out
  testing/nbft/static-broken-json-01/nbft-hfi.json
  testing/nbft/static-broken-json-01/nbft.out
  testing/nbft/static-invalid-ip/nbft-hfi.json
  testing/nbft/static-invalid-ip/nbft.out
  testing/nbft/static-no-index/nbft-hfi.json
  testing/nbft/static-no-index/nbft.out
  testing/nbft/static-no-mac/nbft-hfi.json
  testing/nbft/static-no-mac/nbft.out
  testing/nbft/static-no-prefix/nbft-hfi.json
  testing/nbft/static-no-prefix/nbft.out
  testing/nbft/static-routed-vlan/nbft-hfi.json
  testing/nbft/static-routed-vlan/nbft.out
  testing/nbft/static-routed/nbft-hfi.json
  testing/nbft/static-routed/nbft.out
  testing/nbft/static-vlan/nbft-hfi.json
  testing/nbft/static-vlan/nbft.out
Labels: feature

#951 version 0.6.72
  VERSION
Labels: bug, enhancement, feature
