Repository openSUSE/wicked, pull requests merged in 2024-07, with the labels that each got.

#1023 client: fix crash in hierarchy traversing (bsc#1226664)
  autoip4/autoip.h
  autoip4/device.c
  client/ethtool.c
  client/redfish.c
  client/suse/compat-suse.c
  include/wicked/netinfo.h
  include/wicked/types.h
  src/addrconf.c
  src/auto6.c
  src/bonding.c
  src/capture.c
  src/dhcp4/device.c
  src/ethernet.c
  src/ethtool.c
  src/fsm.c
  src/icmpv6.c
  src/iflist.c
  src/netdev.c
  src/netinfo.c
  src/ovs.c
  src/ppp.c
  src/pppd.c
  src/route.c
  src/update.c
  src/wpa-supplicant.c
Labels: bug

#1024 wireless: add frequency-list in station mode (jsc#PED-8715)
  client/compat.c
  client/ifstatus.c
  client/suse/compat-suse.c
  include/wicked/util.h
  include/wicked/wireless.h
  man/ifcfg-wireless.5.in
  man/src/ifcfg-wireless.5.md
  schema/wireless.xml
  src/dbus-objects/wireless.c
  src/util.c
  src/wireless.c
  src/wpa-supplicant.c
Labels: feature

#1026 client: fix to set and use origin in loaded config (bsc#1226125)
  client/ifcheck.c
  client/ifreload.c
  client/ifstatus.c
  client/ifup.c
  client/nanny.c
  client/read-config.c
  client/wicked-client.h
  src/client/policy.c
Labels: bug

#1028 version 0.6.76
  VERSION
Labels: bug, enhancement, feature
